import {
  DEFAULT_EMOTE_SLUGS,
  EMOTE_CATALOG_ITEMS,
} from "./customizationCatalog.js";

export const EMOJI_PREVIEW_ITEMS = EMOTE_CATALOG_ITEMS;

export const MAX_EMOJI_QUICK_ACCESS_ITEMS = 3;

export const DEFAULT_EMOJI_QUICK_ACCESS_IDS = DEFAULT_EMOTE_SLUGS.slice(
  0,
  MAX_EMOJI_QUICK_ACCESS_ITEMS
);
